region = "us-west-2"
redshift_role_name = "my-redshift-role"
redshift_security_group_name = "my-redshift-sg"
vpc_id = "vpc-123456789"
redshift_secret_name = "my-redshift-credentials"
master_username = "admin"
master_password = "password123"
notebook_name = "my-notebook"
instance_type = "ml.t2.medium"
subnet_id = "subnet-123456789"
sagemaker_security_group_id = "sg-123456789"
redshift_host = "my-redshift-cluster.amazonaws.com"
redshift_database = "my-redshift-db"

